---
title: "DLA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DLA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# DLA testing

```{r setup}
library(BIGDAWGv2)
```

## Run

### 2.) Run the Labrador (Lab) test data making sure to select
### 'dla' as the species parameter

```{r run}

library(BIGDAWGv2)

#Select your species:
Species <- 'dla'

#Select your input data:
Data <- BIGDAWGv2::lab_data
#Data <- BIGDAWGv2::akitaData  

#Choose your loci of interest:
LociSet <- list('DRB1','DQA1')

#Set your output directory:
resultsDir <- '<path/to/output/dir>'

#Set your other parameters and run BIGDAWGv2:
bigdawg.results <- BIGDAWGv2(
  Data         = Data,
  Species      = Species,
  HLA          = FALSE,
  Run.Tests    = c('HWE', 'A'),
  Loci.Set     = LociSet, #Must be a list or will throw an error
  Exon         = c(1),
  All.Pairwise = FALSE,
  Trim         = FALSE,
  Res          = 2,
  EVS.rm       = FALSE,
  Missing      = 2,
  Strict.Bin   = FALSE,
  Cores.Lim    = 1L,
  Results.Dir  = ResultsDir,
  Return       = TRUE,
  Output       = TRUE,
  Merge.Output = FALSE,
  Verbose      = TRUE)

```

*end vignette*
